# Versi칩n de la sintaxis de Docker Compose
version: '3.8'

# Definici칩n de los servicios (contenedores)
services:
  # Nombra tu servicio como quieras
  portfolio-web:
    # "build: ." le dice a Compose que busque un Dockerfile
    # en el directorio actual ('.') y lo construya.
    build: .
    
    # Mapea el puerto de tu m치quina (HOST) al puerto del contenedor (CONTAINER)
    # "8080:80" significa:
    # El puerto 8080 de tu PC (Host) se conectar치 al puerto 80 de Nginx (Contenedor).
    ports:
      - "8080:80"