version: '3.8'

services:
  portafolio:
    build: .
    container_name: portafolio-web
    ports:
      # Mapea el puerto 8080 de tu PC al puerto 80 del contenedor Nginx
      - "8080:80"
    restart: unless-stopped
